name: Build and Replace S3 Bucket Content

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: string
        options:
        - prod

env:
  DEPLOY_ENV: ${{ github.event.inputs.environment || 'dev' }}

jobs:
  build-and-replace-s3-content:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Tag version
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN }}
          tag: ${{ env.DEPLOY_ENV }}-${{ github.run_id }}
      - name: Install NPM dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Configure AWS credentials
        run: |
          echo "[default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Determine Bucket Name
        id: get_bucket_name
        run: |
          if [[ ${{ env.DEPLOY_ENV }} == "dev" ]]; then
            echo "enriqueizquierdo.click"
          else
            echo "enriqueizquierdo.click"
          fi

      - name: Replace S3 bucket content
        run: |
          aws s3 sync ./build "s3://${{ steps.get_bucket_name.outputs.bucket_name }}"
